builds:
  - 
    id: envsecrets
    binary: envsecrets
    main: ./cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -X github.com/envsecrets/envsecrets/cli/commons.VERSION={{.Version}}
      - -X github.com/envsecrets/envsecrets/cli/commons.API=https://envsecrets-3dizc5e3rq-el.a.run.app
      - -X github.com/envsecrets/envsecrets/config/commons.NHOST_AUTH_URL=https://vtlttqmxlifmlwsrvddp.auth.eu-central-1.nhost.run/v1
      - -X github.com/envsecrets/envsecrets/cli/commons.NHOST_AUTH_URL=https://vtlttqmxlifmlwsrvddp.auth.eu-central-1.nhost.run/v1
      - -X github.com/envsecrets/envsecrets/cli/commons.NHOST_GRAPHQL_URL=https://vtlttqmxlifmlwsrvddp.graphql.eu-central-1.nhost.run/v1

release:
  prerelease: auto

  # We want to publish our binaries in a different public repository.
  github:
    owner: envsecrets
    name: cli

universal_binaries:
  - replace: true

brews:
  -
    name: envsecrets
    homepage: "https://envsecrets.com"
    description: "CLI-first management of your environment secrets."
    download_strategy: CurlDownloadStrategy

    tap:
      owner: envsecrets
      name: homebrew-tap
    commit_author:
      name: mrinalwahal
      email: mrinalwahal@gmail.com

checksum:
  name_template: 'checksums.txt'