builds:
  - 
    id: envsecrets
    binary: envsecrets
    main: ./cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -X github.com/envsecrets/envsecrets/cli/commons.VERSION={{.Version}}
      - -X github.com/envsecrets/envsecrets/cli/commons.API=https://envsecrets-3dizc5e3rq-el.a.run.app
      - -X github.com/envsecrets/envsecrets/config/commons.NHOST_AUTH_URL=https://vtlttqmxlifmlwsrvddp.auth.eu-central-1.nhost.run/v1
      - -X github.com/envsecrets/envsecrets/cli/commons.NHOST_AUTH_URL=https://vtlttqmxlifmlwsrvddp.auth.eu-central-1.nhost.run/v1
      - -X github.com/envsecrets/envsecrets/cli/commons.NHOST_GRAPHQL_URL=https://vtlttqmxlifmlwsrvddp.graphql.eu-central-1.nhost.run/v1

release:
  prerelease: auto

  # We want to publish our binaries in a different public repository.
  github:
    owner: envsecrets
    name: cli


universal_binaries:
  - replace: true

# To publish to "snap" on Linux distros.
snapcrafts:
  -
    # The name of the snap. This is optional.
    # Default is project name.
    name: envsecrets

    # Whether to publish the snap to the snapcraft store.
    # Remember you need to `snapcraft login` first.
    # Defaults to false.
    publish: true

    # Single-line elevator pitch for your amazing snap.
    # 79 char long at most.
    summary: "CLI-first management of your environment secrets."

    # This the description of your snap. You have a paragraph or two to tell the
    # most important story about your snap. Keep it under 100 words though,
    # we live in tweetspace and your description wants to look good in the snap
    # store.
    description: |
      Creating an inclusive work environment is imperative to a healthy,
      supportive, and productive culture, and an environment where everyone
      feels welcome and included. woke is a text file analysis tool that finds
      places within your source code that contain non-inclusive language and
      suggests replacing them with more inclusive alternatives.
    
    grade: stable
    base: core20

    confinement: strict

# To publish "brew" packages on MacOS.
brews:
  -
    name: envsecrets
    homepage: "https://envsecrets.com"
    description: "CLI-first management of your environment secrets."
    download_strategy: CurlDownloadStrategy

    tap:
      owner: envsecrets
      name: homebrew-tap
    commit_author:
      name: mrinalwahal
      email: mrinalwahal@gmail.com

checksum:
  name_template: 'checksums.txt'