builds:
  - binary: envsecrets
    main: ./cli
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -X cli/commons.VERSION={{.Version}}
      - -X cli/commons.API=https://envsecrets-3dizc5e3rq-el.a.run.app
      - -X config/commons.NHOST_AUTH_URL=https://vtlttqmxlifmlwsrvddp.auth.eu-central-1.nhost.run/v1
      - -X cli/commons.NHOST_AUTH_URL=https://vtlttqmxlifmlwsrvddp.auth.eu-central-1.nhost.run/v1
      - -X cli/commons.NHOST_GRAPHQL_URL=http://localhost:1337/v1/graphql

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: envsecrets
    homepage: "https://github.com/envsecrets/envsecrets"
    tap:
      owner: mrinalwahal
      name: homebrew-tap
    commit_author:
      name: mrinalwahal
      email: mrinalwahal@gmail.com

checksum:
  name_template: 'checksums.txt'