table:
  name: secrets
  schema: public
object_relationships:
  - name: environment
    using:
      foreign_key_constraint_on: env_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
insert_permissions:
  - role: user
    permission:
      check:
        _or:
          - environment:
              user_id:
                _eq: X-Hasura-User-Id
          - environment:
              project:
                user_id:
                  _eq: X-Hasura-User-Id
          - environment:
              project:
                organisation:
                  user_id:
                    _eq: X-Hasura-User-Id
          - environment:
              project:
                organisation:
                  org_has_user:
                    _and:
                      - user_id:
                          _eq: X-Hasura-User-Id
                      - role:
                          _or:
                            - permissions:
                                _contains:
                                  environments:
                                    update: true
                            - permissions:
                                _contains:
                                  environments:
                                    create: true
      set:
        user_id: x-hasura-User-Id
      columns:
        - data
        - env_id
        - version
select_permissions:
  - role: user
    permission:
      columns:
        - version
        - data
        - created_at
        - updated_at
        - env_id
        - id
        - user_id
      filter:
        _or:
          - environment:
              user_id:
                _eq: X-Hasura-User-Id
          - environment:
              project:
                user_id:
                  _eq: X-Hasura-User-Id
          - environment:
              project:
                organisation:
                  user_id:
                    _eq: X-Hasura-User-Id
          - environment:
              project:
                organisation:
                  org_has_user:
                    _and:
                      - user_id:
                          _eq: X-Hasura-User-Id
                      - role:
                          permissions:
                            _contains:
                              environments:
                                read: true
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns: []
      filter:
        _or:
          - environment:
              user_id:
                _eq: X-Hasura-User-Id
          - environment:
              project:
                user_id:
                  _eq: X-Hasura-User-Id
          - environment:
              project:
                organisation:
                  user_id:
                    _eq: X-Hasura-User-Id
          - environment:
              project:
                organisation:
                  org_has_user:
                    _and:
                      - user_id:
                          _eq: X-Hasura-User-Id
                      - role:
                          permissions:
                            _contains:
                              environments:
                                update: true
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        _or:
          - environment:
              user_id:
                _eq: X-Hasura-User-Id
          - environment:
              project:
                user_id:
                  _eq: X-Hasura-User-Id
          - environment:
              project:
                organisation:
                  user_id:
                    _eq: X-Hasura-User-Id
          - environment:
              project:
                organisation:
                  org_has_user:
                    _and:
                      - user_id:
                          _eq: X-Hasura-User-Id
                      - role:
                          permissions:
                            _contains:
                              environments:
                                delete: true
event_triggers:
  - name: secret_new
    definition:
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns:
          - data
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API}}/v1/triggers/secrets/new'
    headers:
      - name: x-hasura-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
