table:
  name: environments
  schema: public
object_relationships:
  - name: project
    using:
      foreign_key_constraint_on: project_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
array_relationships:
  - name: env_level_permissions
    using:
      foreign_key_constraint_on:
        column: env_id
        table:
          name: env_level_permissions
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        _or:
          - project:
              organisation:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              project_level_permissions:
                _and:
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - permissions:
                      _contains:
                        environments_manage: true
          - project:
              organisation:
                org_level_permissions:
                  _and:
                    - user_id:
                        _eq: X-Hasura-User-Id
                    - permissions:
                        _contains:
                          projects_manage: true
      set:
        user_id: x-hasura-User-Id
      columns:
        - name
        - project_id
select_permissions:
  - role: user
    permission:
      columns:
        - name
        - created_at
        - updated_at
        - id
        - project_id
        - user_id
      filter:
        _or:
          - user_id:
              _eq: X-Hasura-User-Id
          - project:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              organisation:
                user_id:
                  _eq: X-Hasura-User-Id
          - env_level_permissions:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              project_level_permissions:
                _and:
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - permissions:
                      _contains:
                        environments_manage: true
          - project:
              organisation:
                org_level_permissions:
                  _and:
                    - user_id:
                        _eq: X-Hasura-User-Id
                    - permissions:
                        _contains:
                          projects_manage: true
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - name
      filter:
        _or:
          - project:
              organisation:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              project_level_permissions:
                _and:
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - permissions:
                      _contains:
                        environments_manage: true
          - project:
              organisation:
                org_level_permissions:
                  _and:
                    - user_id:
                        _eq: X-Hasura-User-Id
                    - permissions:
                        _contains:
                          projects_manage: true
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        _or:
          - project:
              organisation:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              project_level_permissions:
                _and:
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - permissions:
                      _contains:
                        environments_manage: true
          - project:
              organisation:
                org_level_permissions:
                  _and:
                    - user_id:
                        _eq: X-Hasura-User-Id
                    - permissions:
                        _contains:
                          projects_manage: true
