table:
  name: events
  schema: public
object_relationships:
  - name: environment
    using:
      foreign_key_constraint_on: env_id
  - name: integration
    using:
      foreign_key_constraint_on: integration_id
insert_permissions:
  - role: user
    permission:
      check:
        integration:
          organisation:
            user_id:
              _eq: X-Hasura-User-Id
      columns:
        - entity_details
        - env_id
        - integration_id
select_permissions:
  - role: user
    permission:
      columns:
        - created_at
        - entity_details
        - env_id
        - id
        - integration_id
        - updated_at
      filter:
        integration:
          organisation:
            user_id:
              _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - entity_details
      filter:
        integration:
          organisation:
            user_id:
              _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        integration:
          organisation:
            user_id:
              _eq: X-Hasura-User-Id
event_triggers:
  - name: event_created
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API}}/v1/triggers/events/new'
    headers:
      - name: x-hasura-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
