table:
  name: invites
  schema: public
object_relationships:
  - name: organisation
    using:
      foreign_key_constraint_on: org_id
  - name: role
    using:
      foreign_key_constraint_on: role_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
insert_permissions:
  - role: user
    permission:
      check:
        _and:
          - _or:
              - organisation:
                  user_id:
                    _eq: X-Hasura-User-Id
              - organisation:
                  org_has_user:
                    _and:
                      - user_id:
                          _eq: X-Hasura-User-Id
                      - role:
                          permissions:
                            _contains:
                              permissions:
                                create: true
          - organisation:
              invite_limit:
                _gt: 0
      set:
        user_id: x-hasura-User-Id
      columns:
        - email
        - org_id
        - role_id
select_permissions:
  - role: user
    permission:
      columns:
        - accepted
        - created_at
        - email
        - id
        - key
        - org_id
        - role_id
        - updated_at
        - user_id
      filter:
        _or:
          - organisation:
              user_id:
                _eq: X-Hasura-User-Id
          - organisation:
              org_has_user:
                _and:
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - role:
                      permissions:
                        _contains:
                          permissions:
                            read: true
          - email:
              _eq: X-Hasura-User-Email
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - accepted
      filter:
        email:
          _eq: X-Hasura-User-Email
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        _or:
          - organisation:
              user_id:
                _eq: X-Hasura-User-Id
          - organisation:
              org_has_user:
                _and:
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - role:
                      permissions:
                        _contains:
                          permissions:
                            delete: true
event_triggers:
  - name: invite_new
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{API}}/v1/triggers/invites/new'
    headers:
      - name: x-hasura-webhook-secret
        value_from_env: NHOST_WEBHOOK_SECRET
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
