table:
  name: environments
  schema: public
object_relationships:
  - name: project
    using:
      foreign_key_constraint_on: project_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
array_relationships:
  - name: env_level_permissions
    using:
      foreign_key_constraint_on:
        column: env_id
        table:
          name: env_level_permissions
          schema: public
  - name: events
    using:
      foreign_key_constraint_on:
        column: env_id
        table:
          name: events
          schema: public
  - name: secrets
    using:
      foreign_key_constraint_on:
        column: env_id
        table:
          name: secrets
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        _or:
          - project:
              organisation:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              organisation:
                org_has_user:
                  _and:
                    - user_id:
                        _eq: X-Hasura-User-Id
                    - role:
                        permissions:
                          _contains:
                            environments:
                              create: true
      set:
        user_id: x-hasura-User-Id
      columns:
        - name
        - project_id
select_permissions:
  - role: user
    permission:
      columns:
        - name
        - created_at
        - updated_at
        - id
        - project_id
        - user_id
      filter:
        _or:
          - project:
              organisation:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              organisation:
                org_has_user:
                  _and:
                    - user_id:
                        _eq: X-Hasura-User-Id
                    - role:
                        permissions:
                          _contains:
                            environments:
                              read: true
          - user_id:
              _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - name
      filter:
        _or:
          - project:
              organisation:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              organisation:
                org_has_user:
                  _and:
                    - user_id:
                        _eq: X-Hasura-User-Id
                    - role:
                        permissions:
                          _contains:
                            environments:
                              update: true
          - user_id:
              _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        _or:
          - project:
              organisation:
                user_id:
                  _eq: X-Hasura-User-Id
          - project:
              user_id:
                _eq: X-Hasura-User-Id
          - project:
              organisation:
                org_has_user:
                  _and:
                    - user_id:
                        _eq: X-Hasura-User-Id
                    - role:
                        permissions:
                          _contains:
                            environments:
                              delete: true
          - user_id:
              _eq: X-Hasura-User-Id
