table:
  name: environments
  schema: public
object_relationships:
  - name: project
    using:
      foreign_key_constraint_on: project_id
array_relationships:
  - name: branches
    using:
      foreign_key_constraint_on:
        column: environment_id
        table:
          name: branches
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        project:
          workspace:
            memberships:
              user_id:
                _eq: X-Hasura-User-Id
      columns:
        - name
        - project_id
select_permissions:
  - role: user
    permission:
      columns:
        - name
        - created_at
        - updated_at
        - id
        - project_id
      filter:
        project:
          workspace:
            memberships:
              user_id:
                _eq: X-Hasura-User-Id
      allow_aggregations: true
update_permissions:
  - role: user
    permission:
      columns:
        - name
      filter:
        project:
          workspace:
            memberships:
              user_id:
                _eq: X-Hasura-User-Id
      check: null
delete_permissions:
  - role: user
    permission:
      filter:
        project:
          workspace:
            user_id:
              _eq: X-Hasura-User-Id
