-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."organisations" add column "serverCopy" text
--  not null unique;
