-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."organisations" add column "invite_limit" integer
--  not null default '2';
