[global]
[[global.environment]]
name = 'API'
value = '{{ secrets.API }}'

[hasura]
version = 'v2.29.0-ce'
adminSecret = '{{ secrets.NHOST_ADMIN_SECRET }}'
webhookSecret = '{{ secrets.NHOST_WEBHOOK_SECRET }}'

[[hasura.jwtSecrets]]
type = 'HS256'
key = '{{ secrets.NHOST_JWT_SECRET }}'

[hasura.settings]
corsDomain = ['*']
devMode = true
enableAllowList = false
enableConsole = true
enableRemoteSchemaPermissions = false
enabledAPIs = ['metadata', 'graphql', 'pgdump', 'config']

[hasura.logs]
level = 'warn'

[hasura.events]
httpPoolSize = 100

[functions]
[functions.node]
version = 18

[auth]
version = '0.21.2'

[auth.redirections]
clientUrl = '{{ secrets.CLIENT_URL }}'
allowedUrls = ['http://localhost:3000']

[auth.signUp]
enabled = false

[auth.user]
[auth.user.roles]
default = 'user'
allowed = ['user', 'me']

[auth.user.locale]
default = 'en'
allowed = ['en']

[auth.user.gravatar]
enabled = true
default = 'retro'
rating = 'g'

[auth.user.email]

[auth.user.emailDomains]

[auth.session]
[auth.session.accessToken]
expiresIn = 14400

[[auth.session.accessToken.customClaims]]
key = 'User-Email'
value = 'email'

[auth.session.refreshToken]
expiresIn = 2592000

[auth.method]
[auth.method.anonymous]
enabled = false

[auth.method.emailPasswordless]
enabled = true

[auth.method.emailPassword]
hibpEnabled = false
emailVerificationRequired = true
passwordMinLength = 8

[auth.method.smsPasswordless]
enabled = false

[auth.method.oauth]
[auth.method.oauth.apple]
enabled = false

[auth.method.oauth.azuread]
tenant = 'common'
enabled = false

[auth.method.oauth.bitbucket]
enabled = false

[auth.method.oauth.discord]
enabled = false

[auth.method.oauth.facebook]
enabled = false

[auth.method.oauth.github]
enabled = true
clientId = '{{ secrets.GITHUB_CLIENT_ID }}'
clientSecret = '{{ secrets.GITHUB_CLIENT_SECRET }}'

[auth.method.oauth.gitlab]
enabled = false

[auth.method.oauth.google]
enabled = true
clientId = '{{ secrets.GOOGLE_CLIENT_ID }}'
scope = ['email', 'profile']
clientSecret = '{{ secrets.GOOGLE_CLIENT_SECRET }}'

[auth.method.oauth.linkedin]
enabled = false

[auth.method.oauth.spotify]
enabled = false

[auth.method.oauth.strava]
enabled = false

[auth.method.oauth.twitch]
enabled = false

[auth.method.oauth.twitter]
enabled = false

[auth.method.oauth.windowslive]
enabled = false

[auth.method.oauth.workos]
enabled = false

[auth.method.webauthn]
enabled = false

[auth.method.webauthn.relyingParty]
name = 'envsecrets'

[auth.method.webauthn.attestation]
timeout = 0

[auth.totp]
enabled = true
issuer = 'envsecrets'

[postgres]
version = '14.6-20230705-1'

[provider]
[provider.smtp]
user = '{{ secrets.SMTP_USERNAME }}'
password = '{{ secrets.SMTP_PASSWORD }}'
sender = '{{ secrets.SMTP_USERNAME }}'
host = '{{ secrets.SMTP_HOST }}'
port = 587
secure = false
method = 'LOGIN'

[storage]
version = '0.3.5'

[observability]
[observability.grafana]
adminPassword = '{{ secrets.GRAFANA_ADMIN_PASSWORD }}'
